# Main menu navigation (å°èˆªç›®éŒ„)
# --------------------------------------

# format: name: link || icon
# sub-menu
# name || icon:
#   name || link || icon

# menu:
#   Home: / || fas fa-home
#   Archives: /archives/ || fas fa-archive
#   Tags: /tags/ || fas fa-tags
#   Categories: /categories/ || fas fa-folder-open
#   Docs||fas fa-book:
#     - ğŸš€ å¿«é€Ÿé–‹å§‹ || /posts/21cfbf15/
#     - ğŸ“‘ ä¸»é¡Œé é¢ || /posts/dc584b87/
#     - ğŸ›  ä¸»é¡Œé…ç½® || /posts/4aa8abbe/
#     - â“ ä¸»é¡Œå•ç­” || /posts/98d20436/
#     - âš¡ï¸ é€²éšæ•™ç¨‹ || /posts/4073eda/
#     - âœ¨ æ›´æ–°æ—¥èªŒ || /posts/198a4240/
#   List||fas fa-list:
#     - Music || /music/ || fas fa-music
#     - Gallery || /Gallery/ || fas fa-images
#     - Movie || /movies/ || fas fa-video
#   Link: /link/ || fas fa-link
#   About: /about/ || fas fa-heart

menu:
  é¦–é : / || fas fa-home
  ç›®éŒ„ || fas fa-compass:
    æ­¸æª”: /archives/ || fas fa-archive
    æ¨™ç±¤: /tags/ || fas fa-tags
    åˆ†é¡: /categories/ || fas fa-folder-open
  æ–‡æª” || fas fa-book:
    ğŸš€ å¿«é€Ÿé–‹å§‹: /posts/21cfbf15/
    ğŸ“‘ ä¸»é¡Œé é¢: /posts/dc584b87/
    ğŸ›  ä¸»é¡Œé…ç½®-1: /posts/4aa8abbe/
    âš”ï¸ ä¸»é¡Œé…ç½®-2: /posts/ceeb73f/
    â“ ä¸»é¡Œå•ç­”: /posts/98d20436/
    âš¡ï¸ é€²éšæ•™ç¨‹: /posts/4073eda/
    âœ¨ æ›´æ–°æ—¥èªŒ: /posts/198a4240/
  # å¨±ä¹||fa fa-heartbeat:
    # - éŸ³æ¨‚ || /music/ || fas fa-music
    # åœ–åº«: /Gallery/ || fas fa-images
  ç•™è¨€æ¿: /messageboard/ || fas fa-comment-dots
  å‹é“¾: /link/ || fas fa-thumbs-up
