# Main menu navigation (å°èˆªç›®éŒ„)
# --------------------------------------

# format: name: link || icon
# sub-menu
# name || icon:
#   name || link || icon

# menu:
#   Home: / || fas fa-home
#   Archives: /archives/ || fas fa-archive
#   Tags: /tags/ || fas fa-tags
#   Categories: /categories/ || fas fa-folder-open
#   Docs||fas fa-book:
#     - ğŸš€ å¿«é€Ÿé–‹å§‹ || /posts/21cfbf15/
#     - ğŸ“‘ ä¸»é¡Œé é¢ || /posts/dc584b87/
#     - ğŸ›  ä¸»é¡Œé…ç½® || /posts/4aa8abbe/
#     - â“ ä¸»é¡Œå•ç­” || /posts/98d20436/
#     - âš¡ï¸ é€²éšæ•™ç¨‹ || /posts/4073eda/
#     - âœ¨ æ›´æ–°æ—¥èªŒ || /posts/198a4240/
#   List||fas fa-list:
#     - Music || /music/ || fas fa-music
#     - Gallery || /Gallery/ || fas fa-images
#     - Movie || /movies/ || fas fa-video
#   Link: /link/ || fas fa-link
#   About: /about/ || fas fa-heart

menu:
  é¦–é : / || fas fa-home
  ç›®éŒ„ || fas fa-compass:
    æ­¸æª”: /archives/ || fas fa-archive
    æ¨™ç±¤: /tags/ || fas fa-tags
    åˆ†é¡: /categories/ || fas fa-folder-open
  æ–‡æª” || fas fa-book:
    ğŸš€ å¿«é€Ÿé–‹å§‹: /posts/21cfbf15/
    ğŸ“‘ ä¸»é¡Œé é¢: /posts/dc584b87/
    ğŸ›  ä¸»é¡Œé…ç½®-1: /posts/4aa8abbe/
    âš”ï¸ ä¸»é¡Œé…ç½®-2: /posts/ceeb73f/
    â“ ä¸»é¡Œå•ç­”: /posts/98d20436/
    âš¡ï¸ é€²éšæ•™ç¨‹: /posts/4073eda/
    âœ¨ æ›´æ–°æ—¥èªŒ: /posts/198a4240/
  # å¨±ä¹||fa fa-heartbeat:
  # - éŸ³æ¨‚ || /music/ || fas fa-music
  # åœ–åº«: /Gallery/ || fas fa-images
  ç•™è¨€æ¿: /messageboard/ || fas fa-comment-dots
  å‹é“¾: /link/ || fas fa-thumbs-up

# Code Blocks (ä»£ç¢¼ç›¸é—œ)
# --------------------------------------

highlight_theme: mac # darker / pale night / light / ocean / mac / mac light /false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 400 # unit: px
code_word_wrap: false

# copy settings
# copyright: Add the copyright information after copied content (è¤‡è£½çš„å…§å®¹å¾Œé¢åŠ ä¸Šç‰ˆæ¬Šä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 150

# social settings (ç¤¾äº¤åœ–æ¨™è¨­ç½®)
# --------------------------------------
# formal:
#   icon: link || the description
social:
  fab fa-github: https://github.com/zhaoqianguo || Github
  fas fa-envelope: mailto:844851879@qq.com || Email
  # fas fa-rss: /atom.xml || RSS
# search (æœç´¢)
# --------------------------------------

# Algolia search
# algolia_search:
#   enable: false
#   hits:
#     per_page: 6

# # Local search
# local_search:
#   enable: true
#   preload: false
#   CDN:

# Image (åœ–ç‰‡è¨­ç½®)
# --------------------------------------

# Faviconï¼ˆç¶²ç«™åœ–æ¨™ï¼‰
favicon: /assets/images/favicon.png

# Avatar (é ­åƒ)
avatar:
  img: /assets/images/avatar.avif
  effect: false

# The banner image of home page
index_img: /assets/images/index_img.jpg

# If the banner of page not setting, it will show the top_img
default_top_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/index.jpg

# The banner image of archive page
archive_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/archive.jpg

# If the banner of tag page not setting, it will show the top_img
# note: tag page, not tags page (å­æ¨™ç±¤é é¢çš„ top_img)
tag_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/tag.png

# The banner image of tag page
# format:
#  - tag name: xxxxx
# tag_per_img:

# If the banner of category page not setting, it will show the top_img
# note: category page, not categories page (å­åˆ†é¡é é¢çš„ top_img)
category_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/category.jpg

# The banner image of category page
# format:
#  - category name: xxxxx
category_per_img:

cover:
  # display the cover or not (æ˜¯å¦é¡¯ç¤ºæ–‡ç« å°é¢)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (å°é¢é¡¯ç¤ºçš„ä½ç½®)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (ç•¶æ²’æœ‰è¨­ç½®coveræ™‚ï¼Œé»˜èªçš„å°é¢é¡¯ç¤º)
  default_cover: # https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/default.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-2.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-1.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-3.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-6.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-5.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-4.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-7.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-9.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-8.png
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN/img/material-10.png

# Replace Broken Images (æ›¿æ›ç„¡æ³•é¡¯ç¤ºçš„åœ–ç‰‡)
# error_img:
#   flink: /img/friend_404.gif
#   post_page: /img/404.jpg

# A simple 404 page
# error_404:
#   enable: true
#   subtitle: "é é¢æ²’æœ‰æ‰¾åˆ°"
#   background:

post_meta:
  page: # Home Page
    date_type: created # created or updated or both ä¸»é æ–‡ç« æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: true # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: false # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: created # created or updated or both æ–‡ç« é æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: true # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: true # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—

# wordcount (å­—æ•¸çµ±è¨ˆ)
# wordcount:
#   enable: true
#   post_wordcount: true
#   min2read: true
#   total_wordcount: true

# aside (å´é‚Šæ¬„)
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: follow me
      link: https://github.com/zhaoqianguo
  card_announcement: # å…¬å‘Š
    enable: true
    content: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹å³å°†å‘ç”ŸğŸ˜
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 0 # if set 0 will show all
    expand: false # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: YYYYå¹´MMæœˆ # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# Bottom right button (å³ä¸‹è§’æŒ‰éˆ•)
# --------------------------------------

# Read Mode (é–²è®€æ¨¡å¼)
readmode: true

# dark mode
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (è‡ªå‹•åˆ‡æ› dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: 1
